### ISSUE TITLE
Wireframes for physical product UI

### ISSUE THREAD

**Issue by amolakplaha** [fahimbyte/Smart-Trash-Can#50]

**Comment by f-0-o** [comment]
Pages:

1. Welcome/Start page.
   1.1 Enter the name of the user(s).
2. (While Idle) Show the fullness of the trash can on OLED.
3. Press the middle button to bring up the user selection page. 
4. Select the user who is about to take out the trash.
5. Once the lid is closed, give the current user credit.

**Comment by f-0-o** [comment]
[Hardware Wireframe.pdf](https://github.com/f-0-o/Smart-Trash-Can/files/8329434/Hardware.Wireframe.pdf)

**Comment by f-0-o** [comment]
[Hardware Wireframe.pdf](https://github.com/f-0-o/Smart-Trash-Can/files/8329436/Hardware.Wireframe.pdf)
